language: java
sudo: false
script: mvn test
jdk:
- openjdk8
- oraclejdk8
env:
  global:
    secure: QrWLe6ckCUvPUKfNUAQXcX8+6Jyf43GY8FrxaIcB18L+38O+JZLe2Xk2czBg793Oap0SDBRyDps6oeaztH34osxD89/EKDOsc08fT8aMKAWHBI2oTciJUe+a3m7d9BYhbUjWTPuH9W/EwC5u5fJmKj4NV81HSLNR7/o6205p9qREEiD6TarTIOpAckT1xKS6JpiUU6hBUw8pKH47CU/tGJTiorhGAzby2D+ekOz4QB2vx5FhjUfQpd2cNM31bceYbj4r/2I8WqCkkqcFt/00ec8aXgzMKLqtSd5WOljwOevx2NEekUIRlMBLyjZCiFRmpEuu+UG3+IOi6N1M0jww6qJwlfKtzNeTFYewPW5mP8dIGe2MGQfeEfIzkTFc2+Idzq9yTDDeVZ8r9DRoBU4f1B3sNUoTFdhwMXtS+IJtDLCPrFtE6f5jQMIeXAs4bYwliTaTSd944wDcQ2l6qCmC0mFvvCR+0BJz0kH8Q3L+WFFS6e6iARqOuQVapozv7I8/w5on+H3Kb/dzwkGRvu7bPBBJzf8R6HowXFQjNKptVZ/aA0J8BgIBKhcvGn+BEJtCQoSPLVdOa9G3bDZwXZjqvCMNeRSPDs25RYjIM5EvvrXH0VF1GLc7pbriR3MSlEF+8GonH+QfBIptTtUdhOjPocJBA+7qeiGEWvIEp16dmUA=
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "openjdk8" ]] &&
  { mvn deploy --settings .travis-settings.xml -DskipTests=true -B; };'
